# Generated by Django 3.0.8 on 2020-08-20 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountId', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('accountType', models.CharField(choices=[('customer', 'Customer'), ('employee', 'Employee')], default='Customer', max_length=100)),
                ('rewardPoints', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('salary', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotelId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('image', models.ImageField(default=None, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelId', models.IntegerField()),
                ('roomId', models.IntegerField()),
                ('accountId', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelId', models.IntegerField()),
                ('roomId', models.IntegerField()),
                ('accountId', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('0', 'waitlisted'), ('1', 'confirmed')], default='0', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomId', models.AutoField(primary_key=True, serialize=False)),
                ('roomType', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('available', models.PositiveIntegerField(default=0)),
                ('hotelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.Hotel')),
            ],
        ),
    ]
