# Generated by Django 3.0.8 on 2020-08-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='hotelName',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='hotelId',
            field=models.IntegerField(),
        ),
    ]
