# Generated by Django 3.0.8 on 2020-08-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0004_auto_20200821_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlist',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed')], default='pending', max_length=100),
        ),
    ]
