# Generated by Django 3.0.8 on 2020-08-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0005_auto_20200821_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlist',
            name='id',
        ),
        migrations.AddField(
            model_name='waitlist',
            name='waitlistId',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
